### ISSUE TITLE
Use docker image with correct imagemagick version on .travis.yml

### ISSUE THREAD

**Issue by ViniciusAlmeidaSilva** [ruby-marks/ruby-marks#27]
It's taking too long, to setup the build every time we need to run it on CI. It tooks like 5 to 6 minutes just for building spec env. Multiply this to four ruby versions and we have something like 25 minutes to have build jobs completely done. If we use the docker image we've got up on performance better than the actual

**Comment by rhiroyuki** [comment]
Hi Vinicius, Im interested in working on this issue :)

Would you mind detailing more about this issue (acceptance criteria)? Is it just to add a docker image for each ruby version?

**Comment by andrerpbts** [comment]
Hello Ricardo,

If you could add a base image with the correct ImageMagick version, it would be enough for now. If you check the root path, you'll see a file named `befor_install_linux.sh`, which basically destroys all ImageMagick previous installed, and reinstall it downloading from IM site. Travis, by default, has an IM available but is kinda older (6.7 I guess). 

The main purpose here is to stop downloading and reinstalling IM every time the build runs. 

So, answering your question, a single image with IM installed would be great, everything else can run as it runs now.

**Comment by andrerpbts** [comment]
Instead of the docker image, we configured the `ccache` directory to avoid reinstall it every run. The build is running around 4 minutes now.
 
Thanks @rhiroyuki.
