### ISSUE TITLE
Help for configuration

### ISSUE THREAD

**Issue by alfredodelfabro** [ruby-marks/ruby-marks#39]
Hello,

all examples provided are with bubble multiple choice answer sheet. 

Is it possible to use this gem with another style, like the one below? I tried and I can only recognize the group.

Original:

<img width="143" alt="teste" src="https://user-images.githubusercontent.com/49418924/93718216-07341d00-fb51-11ea-8dcc-1f7e0c3a592b.png">

Flagged Document:

<img width="143" alt="temp" src="https://user-images.githubusercontent.com/49418924/93718236-2763dc00-fb51-11ea-923d-fbcdc1df4c52.png">

My code:

```
recognizer = RubyMarks::Recognizer.new

recognizer.configure do |config|
  config.threshold_level = 90
  config.default_expected_lines = 30
  config.default_marks_options = %w{A B C D E F}
  config.scan_mode = :grid

  config.default_mark_width = 46
  config.default_mark_height = 28
  config.default_distance_between_marks = 0
  config.intensity_percentual = 30

  config.define_group :first  do |group|
    group.expected_coordinates = {x1: 5, y1: 6, x2: 279, y2: 909}
  end
end

basedir = 'app/assets/images/'
recognizer.file = basedir + 'teste.png'
file = recognizer.file
filename = basedir + "temp_image.png"
file.write(filename)

temp_filename = basedir + "temp.png"
flagged_document = recognizer.flag_all_marks
flagged_document.write(temp_filename)
```

Can you help me or give me a hint on how to move on?
Thanks!

**Comment by andrerpbts** [comment]
Hello @alfredodelfabro,

I'm running some tests here to see what's going on. I'll return to you as soon as I get it.

**Comment by alfredodelfabro** [comment]
Ok, thanks!

If you need any information please let me know.

**Comment by alfredodelfabro** [comment]
I spent some time trying to solve the problem and it looks like I did it.

My code (changes in default_mark_width, default_mark_height, default_distance_between_marks and expected_coordinates):

```
recognizer = RubyMarks::Recognizer.new

recognizer.configure do |config|
  config.threshold_level = 90
  config.default_expected_lines = 30
  config.default_marks_options = %w{A B C D E F}
  config.scan_mode = :grid

  config.default_mark_width = 34
  config.default_mark_height = 24
  config.default_distance_between_marks = 45
  config.intensity_percentual = 30

  config.define_group :first  do |group|
    group.expected_coordinates = {x1: 4, y1: 5, x2: 280, y2: 910}
  end
end

basedir = 'app/assets/images/'
target_file = 'teste.png'
recognizer.file = basedir + target_file
file = recognizer.file
filename = basedir + "temp_image.png"
file.write(filename)

temp_filename = basedir + "temp.png"
flagged_document = recognizer.flag_all_marks
flagged_document.write(temp_filename)
```

And now I'm having the same problem with another image.

Original:

![result_4](https://user-images.githubusercontent.com/49418924/93958367-ba0ca280-fd2c-11ea-8442-59989e7faa75.png)

Image 1:

<img width="118" alt="temp_image" src="https://user-images.githubusercontent.com/49418924/93958400-cb55af00-fd2c-11ea-9682-e7474dad4b3e.png">

Image 2:

<img width="118" alt="temp" src="https://user-images.githubusercontent.com/49418924/93958448-e4f6f680-fd2c-11ea-8778-74b9b075f6c4.png">

My Code:

```
recognizer = RubyMarks::Recognizer.new

recognizer.configure do |config|
  config.threshold_level = 90
  config.default_expected_lines = 12
  config.default_marks_options = %w{A B C D E}
  config.scan_mode = :grid

  config.default_mark_width = 15
  config.default_mark_height = 25
  config.default_distance_between_marks = 45
  config.intensity_percentual = 70

  config.default_mark_width_tolerance = 8
  config.default_mark_height_tolerance = 8


  config.edge_level = 6


  config.define_group :first  do |group|
    group.expected_coordinates = {x1: 0, y1: 0, x2: 234, y2: 823}
  end
end

basedir = 'app/assets/images/'
target_file = 'result_4.png'
recognizer.file = basedir + target_file
file = recognizer.file
filename = basedir + "temp_image.png"
file.write(filename)

temp_filename = basedir + "temp.png"
flagged_document = recognizer.flag_all_marks
flagged_document.write(temp_filename)
```

As you can see, these two images are pretty similar (code too):

<img width="143" alt="temp_image" src="https://user-images.githubusercontent.com/49418924/93958720-82eac100-fd2d-11ea-8e88-6b6fe93ffc24.png"> <img width="143" alt="temp" src="https://user-images.githubusercontent.com/49418924/93958936-02789000-fd2e-11ea-911c-e012c980aa54.png">

<img width="118" alt="temp_image" src="https://user-images.githubusercontent.com/49418924/93958712-7c5c4980-fd2d-11ea-9296-e90c8823ccc3.png"> <img width="118" alt="temp" src="https://user-images.githubusercontent.com/49418924/93958931-fb518200-fd2d-11ea-85e2-4f6fba090a3f.png">

Can you help me understand why in the first case marks are recognized and in the second case they are not?

Thanks!

**Comment by alfredodelfabro** [comment]
I also find that when i do `recognizer.groups.first[1].coordinates` on console for the first case I get `{:x1=>2, :x2=>283, :y1=>0, :y2=>913}` as result.

When I do the same for the second case I get `nil`.

So I think that the problem might be at line 128 from recognizer.rb:

`block = scanner.scan(Magick::Point.new(x, y), width, height)`

Maybe the scan method of FloodScan can't find the coordinates, but I can't understand why.

**Comment by andrerpbts** [comment]
Yes, your problem isn't about the marks, but the group recognition. Can you try to add some blank margins to your image and adjust the expected coordinates to have the group inside it, please? 

Just to make a test...

**Comment by alfredodelfabro** [comment]
Hello,

adding the blank margin seems to have worked. 

Original image:

<img width="269" alt="result_2" src="https://user-images.githubusercontent.com/49418924/94182632-aae63b80-fe77-11ea-96e6-75e5348a62a5.png">

Flagged Image:

<img width="269" alt="temp" src="https://user-images.githubusercontent.com/49418924/94182688-be91a200-fe77-11ea-8fae-fa06c7ad05d7.png">

Can you explain why? I ask why the answer sheet is actually in the following format, and I couldn't get it to work.

![temp](https://user-images.githubusercontent.com/49418924/94182897-03b5d400-fe78-11ea-9f2f-2c3dfb458d29.png)

My strategy would be to define five groups, but if it works only with a blank margin, I don't think I can do it for this case.

Would you have a hint of what I could do? Maybe some image treatment? But for that I need to better understand how group recognition works. I appreciate if you can help me.

**Comment by andrerpbts** [comment]
Yes, the way it works today, the flood scan is expecting a space to separate a group from others. I'm afraid you'll need to work your image before sending it to the recognizer.

You can try to modify this lib to implement a grid for sub-groups, or perhaps you could treat this entire image as a single block, and configure the expected coordinates to make the recognizer identify the correct coordinates. With these coordinates in hand, I think you can explode it in 5 images which will respond to the same expected coordinates, or you can create a new image adding spaces to it.

Currently, I'm a bit overloaded with other tasks and I'm afraid I can't implement this right now, but I'll take a look in the weekend to see if I get any other way to solve that.

**Comment by alfredodelfabro** [comment]
@andrerpbts ,

thank you very much for your help and attention. I'll keep an eye on it and see if I can do something on the weekend too. In the meantime I will try to implement one of your strategies, since I need an MVP until tomorrow, lol.

Thank you again.

**Comment by alfredodelfabro** [comment]
Hello,

eu implementei a tua ideia de dividir a imagem e adicionar espaços em branco com o RMagick. Veja:

![0](https://user-images.githubusercontent.com/49418924/94324177-13641400-ff6f-11ea-8f4a-f6d3d8511fb4.png)
![temp](https://user-images.githubusercontent.com/49418924/94324270-82da0380-ff6f-11ea-95a6-9d17dcdb0a0a.png)


Entretanto, eu estou tendo dificuldades para posicionar as marcas de forma correta. Qual parâmetro que controla o posicoinamento e tamanho das marcas? Já tentei default_mark_width e default_mark_height. Veja o resultado:

`{:first=>{1=>["A"], 2=>[], 3=>[], 4=>[], 5=>["E"], 6=>["A"], 7=>[], 8=>[], 9=>[], 10=>["E"], 11=>[], 12=>["C"]}}`

My Code:

```
recognizer = RubyMarks::Recognizer.new

recognizer.configure do |config|
  config.threshold_level = 90
  config.default_expected_lines = 12
  config.default_marks_options = %w{A B C D E}
  config.scan_mode = :grid

  config.default_mark_width = 70
  config.default_mark_height = 30
  config.default_distance_between_marks = 70
  config.intensity_percentual = 30

  config.edge_level = 6

  config.define_group :first  do |group|
    group.expected_coordinates = {x1: 15, y1: 0, x2: 280, y2: 854}
  end
end

basedir = 'app/assets/images/'
target_file = '0.png'
recognizer.file = basedir + target_file
file = recognizer.file
filename = basedir + "temp_image.png"
file.write(filename)

temp_filename = basedir + "temp.png"
flagged_document = recognizer.flag_all_marks
flagged_document.write(temp_filename)

recognizer.file = basedir + target_file
puts recognizer.scan
```

Thanks again.

**Comment by andrerpbts** [comment]
São essas mesmas, talvez vc precise aumentar um pouco o tamanho da height, diminuir um pouco a default_distance_between_marks  e ajustar intensity_percentual, e vc deve ter um resultado. Uma coisa que percebi no seu gabarito todo é que os blocos em si estão na horizontal (pelo menos a numeração dele), então vc vai ter que fazer uma multiplicação ai pra fazer o assign correto do valor para o numero da linha....

**Comment by andrerpbts** [comment]
Outra coisa, nos gabaritos que trabalhamos quando implementamos essa gem, a gente pedia pra um preenchimento completo (por isso optamos por bubble sheet), preenchendo direitinho aumentava muito a acurácia. Infelizmente seu formulario não ajuda muito, pois não é muito claro onde se está cada marca e dificulta um pouco o reconhecimento, por conta de que a letra ali que informa, conta muito como area preenchida. Perceba que a lib faz um scan binario, preto e branco, ele pega os pixels pretos de cada marca e divide pela area da marca pra saber o quão preenchida ela foi. 30% no seu caso parece aceitável, mas eu percebi ali que tem casos que pegou 27% e era uma area a ser reconhecida, e também pegou 27% de uma area que não era pra ser reconhecida. Então a regra creio que seja, aumentar a area, aumentar um pouco o percentual de reconhecimento (intensity_percentual), E MAIS IMPORTANTE, se estiver no seu comando isso, pedir um preenchimento mais uniforme...

**Comment by alfredodelfabro** [comment]
Muito obrigado pelo retorno @andrerpbts ! Vou tentar modificar esses parâmetros.

**Comment by alfredodelfabro** [comment]
Olá @andrerpbts,

existe alguma forma de retornar sempre um resultado, independente do intensity_percentual? Por exemplo, capturar todas as respostas atreladas ao intensity_percentual e retornar o com maior probabilidade de ser a resposta correta?

**Comment by andrerpbts** [comment]
@alfredodelfabro infelizmente creio que não, acho que teria que implementar algo assim. Você pode dar uma olhada no [scan multiple lines watcher](https://github.com/ruby-marks/ruby-marks#scan-multiple-marked-watcher) e ver se consegue fazer algum tratamento do tipo ali.

**Comment by alfredodelfabro** [comment]
Muito obrigado @andrerpbts !

Consegui um resultado satisfatório. Dei uma brincada rápida! Vou aprimorar o código, mas fiz algo nesse sentido:

```
recognizer.add_watcher :scan_multiple_marked_watcher do |recognizer, result|
          # place your custom code
          resultss = Hash.new { |hash, key| hash[key] = [] }
          resultss.tap do |effect|
            recognizer.groups.each_pair do |_label, group|
              marks = Hash.new { |hash, key| hash[key] = [] }
              group.marks.each_pair do |line, value|
                value.each do |mark|
                  marks[line] << [mark.value, mark.intensity]  if mark.marked? && mark.value
                end
              end

              effect[group.label.to_sym] = marks
            end
          end
          puts resultss
        end
```

E obtive:

`{:first=>{1=>[[“1”, 58], [“3", 41], [“5”, 40]], 2=>[[“2", 43]], 5=>[[“5”, 41]], 6=>[[“3", 41]], 7=>[[“2”, 43]], 10=>[[“5", 44]], 12=>[[“3”, 43]], 13=>[[“2", 40]], 14=>[[“1”, 41]], 15=>[[“3", 41]], 16=>[[“5”, 49]], 17=>[[“4", 48]], 18=>[[“3”, 49]], 19=>[[“2", 55]], 20=>[[“1”, 54]], 21=>[[“2", 55]], 22=>[[“3”, 48]], 23=>[[“4", 52]], 24=>[[“2”, 53]], 25=>[[“1", 56]], 26=>[[“5”, 56]], 27=>[[“1", 56]], 28=>[[“3”, 54]], 29=>[[“2", 59]], 30=>[[“4”, 54]], 31=>[[“3", 50], [“5”, 44]]}}`

**Comment by andrerpbts** [comment]
Muito legal! Que bom que deu certo e parabéns aí pela solução :)

Vou fechar, mas se tiver mais alguma dúvida é só falar!
